"""Main CLI commands for the GetAJob application.

Provides the core Typer commands: init, discover, tailor, run, serve,
doctor, and setup.
"""

from __future__ import annotations as _annotations

import os
import sys
from pathlib import Path

import typer
from rich.panel import Panel
from rich.progress import (
    Progress,
    SpinnerColumn,
    TextColumn,
)

from getajob.cli.helpers import (
    _check_settings,
    _print_result_table,
    _run_async,
    console,
    err_console,
)
from getajob.cli.main import app

__all__: list[str] = [
    "discover",
    "doctor",
    "init",
    "run",
    "serve",
    "setup",
    "tailor",
]


@app.command()
def init(
    force: bool = typer.Option(
        False,
        "--force",
        "-f",
        help="Overwrite existing .env without prompting.",
    ),
) -> None:
    """Interactive first-run wizard for non-technical users.

    Walks through the initial configuration: LLM API key, profile creation,
    default search vectors, and database setup -- all in one step.
    """
    console.print(
        Panel.fit(
            "[bold green]\U0001f680  GetAJob -- First-Run Init[/]",
            border_style="green",
        )
    )

    project_root = Path(__file__).resolve().parent.parent.parent
    env_path = project_root / ".env"

    # Step 1: Check for existing .env.
    if env_path.exists() and not force:
        overwrite = typer.confirm(
            f"  {env_path} already exists.\n  Overwrite existing configuration?",
            default=False,
        )
        if not overwrite:
            console.print("[yellow]  Init cancelled -- no changes made.[/]")
            raise typer.Exit()

    # Step 2: LLM provider & API key.
    console.print("\n[bold]\U0001f916  LLM Configuration[/]")

    existing_key = os.environ.get("GETAJOB_LLM__API_KEY")
    if existing_key:
        api_key = existing_key
        provider = os.environ.get("GETAJOB_LLM__PROVIDER", "anthropic")
        console.print("  [dim]Using GETAJOB_LLM__API_KEY from environment[/]")
    else:
        provider = typer.prompt("  LLM provider", default="anthropic")
        api_key = typer.prompt("  API key", hide_input=True)

    # Step 3: Write .env file.
    model = "claude-sonnet-4-6" if provider.lower() in ("anthropic", "claude") else "gpt-4o"
    encryption_key = os.urandom(32).hex()
    encryption_salt = os.urandom(16).hex()
    tokenizer_salt = os.urandom(16).hex()

    env_content = f"""# GetAJob -- Environment Configuration
# Auto-generated by `getajob init`

GETAJOB_ENVIRONMENT=development
GETAJOB_DEBUG=true
GETAJOB_LOG_FORMAT=console

# -- PostgreSQL ----------------------------------------------------------------
GETAJOB_DATABASE__HOST=localhost
GETAJOB_DATABASE__PORT=5432
GETAJOB_DATABASE__DATABASE=getajob
GETAJOB_DATABASE__USER=getajob
GETAJOB_DATABASE__PASSWORD=change_me_in_production
GETAJOB_DATABASE__MIN_CONNECTIONS=2
GETAJOB_DATABASE__MAX_CONNECTIONS=10

# -- LLM -----------------------------------------------------------------------
GETAJOB_LLM__PROVIDER={provider}
GETAJOB_LLM__API_KEY={api_key if not existing_key else ""}
GETAJOB_LLM__MODEL={model}
GETAJOB_LLM__MAX_TOKENS=4096
GETAJOB_LLM__TEMPERATURE=0.7
GETAJOB_LLM__TIMEOUT_SECONDS=120

# -- Redis ---------------------------------------------------------------------
GETAJOB_REDIS__HOST=localhost
GETAJOB_REDIS__PORT=6379
GETAJOB_REDIS__DB=0

# -- Security / Encryption (auto-generated) ------------------------------------
GETAJOB_SECURITY__ENCRYPTION_KEY={encryption_key}
GETAJOB_SECURITY__ENCRYPTION_SALT={encryption_salt}
GETAJOB_SECURITY__TOKENIZER_SALT={tokenizer_salt}
# GETAJOB_SECURITY__APPROVAL_PASSWORD=

# -- Browser Automation --------------------------------------------------------
GETAJOB_BROWSER__HEADLESS=true
GETAJOB_BROWSER__VIEWPORT_WIDTH=1920
GETAJOB_BROWSER__VIEWPORT_HEIGHT=1080
GETAJOB_BROWSER__LOCALE=en-US
GETAJOB_BROWSER__SLOW_MO_MS=50
GETAJOB_BROWSER__NAVIGATION_TIMEOUT_SECONDS=30

# -- Job Discovery -------------------------------------------------------------
GETAJOB_JOB_DISCOVERY__MAX_APPLICATIONS_PER_DAY=50
"""
    # codeql[py/clear-text-storage-sensitive-data]: False positive
    # .env is local config with 0o600 perms
    env_path.write_text(env_content)
    env_path.chmod(0o600)
    console.print(f"  [green]\u2713[/] Configuration written: {env_path}")

    # Step 4: User profile (optional).
    console.print("\n[bold]\U0001f464  User Profile (optional)[/]")
    console.print("  Provide your name and email to create a profile.")
    name = typer.prompt("  Name", default="")
    email = typer.prompt("  Email", default="")
    has_profile = bool(name and email)

    # Steps 5-7: Async operations.
    async def _run_init() -> None:
        # Force settings reload now that .env exists on disk.
        import core.config as core_config

        core_config._settings = None

        # Step 5: Create user profile in the database.
        if has_profile:
            try:
                from core.database import create_engine
                from core.schemas import ProfileCreate
                from profile_engine.profile_store import ProfileStore

                engine = create_engine()
                store = ProfileStore(engine)
                profile = await store.create_profile(
                    ProfileCreate(
                        name=name,
                        email=email,
                        phone="",
                    )
                )
                console.print(
                    f"  [green]\u2713[/] Profile created: [bold]{profile.name}[/] (id: {profile.id})"
                )
                await engine.dispose()
            except Exception as exc:
                console.print(f"  [yellow]\u26a0[/] Could not create profile: {exc}")
                console.print("    You can create one later by creating a profile directly.")

        # Step 6: Write default search vectors into settings.yaml.
        try:
            from getajob.cli.helpers import _write_default_search_vectors

            _write_default_search_vectors(project_root)
            console.print("  [green]\u2713[/] Default search vectors written to settings.yaml")
        except Exception as exc:
            console.print(f"  [yellow]\u26a0[/] Could not write search vectors: {exc}")

        # Step 7: Database setup (create tables + data directories).
        try:
            from core.config import get_settings
            from core.database import create_engine, run_migrations

            s = get_settings()
            engine = create_engine()
            await run_migrations(engine)

            data_dir = s.data_dir
            data_dir.mkdir(parents=True, exist_ok=True)
            for sub in ("profiles", "resumes", "cover_letters", "screenshots"):
                (data_dir / sub).mkdir(parents=True, exist_ok=True)

            console.print("  [green]\u2713[/] Database schema ready.")
            await engine.dispose()
        except Exception as exc:
            console.print(f"  [yellow]\u26a0[/] Could not initialise database: {exc}")
            console.print("    Ensure PostgreSQL is running and .env is configured correctly.")

    _run_async(_run_init())

    # Step 8: Success summary.
    console.print()
    console.print(
        Panel(
            "[bold green]\u2713[/]  GetAJob initialised successfully!\n\n"
            "  [bold]Next steps:[/]\n"
            "  \u2022 Run [cyan]getajob run[/]        "
            "-- Start discovering jobs\n"
            "  \u2022 Run [cyan]getajob serve[/]      "
            "-- Open the approval queue\n"
            "  \u2022 Edit [cyan].env[/]              "
            "-- Advanced configuration\n"
            "  \u2022 See [cyan]env.template[/]       "
            "-- All available settings\n",
            border_style="green",
            title="Init Complete",
        )
    )


@app.command()
def discover(
    _ctx: typer.Context,
    continuous: bool = typer.Option(
        False,
        "--continuous",
        "-c",
        help="Run discovery continuously on an interval.",
    ),
    interval: float = typer.Option(
        15.0,
        "--interval",
        "-i",
        help="Minutes between discovery passes in continuous mode.",
        min=1.0,
        max=120.0,
    ),
) -> None:
    """Discover job listings from all configured search vectors.

    Executes the orchestrator's discovery phase: loads search vectors from
    config, queries each job source for new listings, runs context analysis
    against the active profile, and creates Application records in DISCOVERED
    state.
    """
    console.print(Panel.fit("[bold blue]\U0001f50d  Job Discovery[/]", border_style="blue"))
    _check_settings()

    async def _run() -> None:
        from agents.orchestrator_agent import OrchestratorAgent
        from core.database import create_engine
        from core.event_bus import InMemoryEventBus
        from core.llm_client import get_llm_client

        engine = create_engine()
        event_bus = InMemoryEventBus()
        llm_client = get_llm_client()

        orchestrator = OrchestratorAgent(
            engine=engine,
            llm_client=llm_client,
            event_bus=event_bus,
        )

        await orchestrator.start()
        try:
            if continuous:
                console.print(
                    "[blue]\u27f3[/] Continuous discovery mode -- press Ctrl+C to stop gracefully.\n"
                )
                import asyncio

                interval_seconds = interval * 60.0
                while True:
                    result = await orchestrator.run_once()
                    _print_result_table(result, title="Discovery Pass Complete")
                    console.print(f"[dim]Sleeping {interval:.0f} min until next pass...[/]\n")
                    await asyncio.sleep(interval_seconds)
            else:
                with Progress(
                    SpinnerColumn(),
                    TextColumn("[progress.description]{task.description}"),
                    console=console,
                    transient=True,
                ) as progress:
                    progress.add_task(description="Discovering jobs...", total=None)
                    result = await orchestrator.run_once()

                _print_result_table(result, title="Discovery Results")
        finally:
            await orchestrator.stop()

    _run_async(_run())


@app.command()
def tailor(
    _ctx: typer.Context,
    job_id: str = typer.Argument(
        ...,
        help="UUID of the job listing to tailor.",
    ),
) -> None:
    """Generate tailored resume and cover letter for a specific job.

    Runs the full analysis + tailoring pipeline for a single job listing
    that has already been discovered.  Loads the job from the database,
    runs ContextAgent to extract requirements, then TailoringAgent to
    produce tailored materials.
    """
    console.print(Panel.fit("[bold green]\U0001f4dd  Job Tailoring[/]", border_style="green"))
    _check_settings()

    async def _run() -> None:
        from sqlalchemy import select

        from agents.context_agent import ContextAgent
        from agents.tailoring_agent import TailoringAgent
        from core.database import create_engine, get_session
        from core.event_bus import InMemoryEventBus
        from core.llm_client import get_llm_client
        from core.models import JobListing

        engine = create_engine()
        event_bus = InMemoryEventBus()
        llm_client = get_llm_client()

        # Load the listing.
        async with get_session(engine) as session:
            stmt = select(JobListing).where(JobListing.id == job_id)
            listing = (await session.execute(stmt)).scalar_one_or_none()

        if listing is None:
            err_console.print(f"[red]\u2717[/] Job listing '{job_id}' not found.")
            raise typer.Exit(code=1)

        rich_format = Panel(
            f"[bold]{listing.title}[/]\n"
            f"  Company: {listing.company}\n"
            f"  Source:  {listing.source}\n"
            f"  URL:     {listing.url or 'N/A'}",
            border_style="green",
            title="Job Details",
        )
        console.print(rich_format)

        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            console=console,
            transient=True,
        ) as progress:
            # Context analysis.
            progress.add_task(description="Analysing job requirements...", total=None)
            context_agent = ContextAgent(
                engine=engine,
                llm_client=llm_client,
                event_bus=event_bus,
            )
            await context_agent.start()
            desc_text = listing.description_json.get("raw", "") if listing.description_json else ""
            analysis = await context_agent.analyze(
                job_id=str(listing.id),
                job_description=desc_text,
            )
            await context_agent.stop()

            console.print(f"\n  Match score: [bold]{analysis.match_score:.1%}[/]")
            if analysis.matching_skills:
                console.print(f"  Matching skills: {', '.join(analysis.matching_skills[:10])}")
            if analysis.missing_skills:
                console.print(
                    f"  [yellow]Missing skills: {', '.join(analysis.missing_skills[:5])}[/]"
                )
            if analysis.warnings:
                for w in analysis.warnings:
                    console.print(f"  [yellow]\u26a0 {w}[/]")
            console.print()

            # Tailoring.
            progress.add_task(description="Generating resume & cover letter...", total=None)
            tailoring_agent = TailoringAgent(
                engine=engine,
                llm_client=llm_client,
                event_bus=event_bus,
            )
            await tailoring_agent.start()
            result = await tailoring_agent.tailor(
                job_listing_id=str(listing.id),
                profile_id=analysis.profile_id,
                job_title=listing.title,
                company=listing.company,
                job_description=desc_text,
                generate_cover_letter=True,
            )
            await tailoring_agent.stop()

        # Display results.
        cov_letter_text = "\u2713 Generated" if result.cover_letter else "\u2717 Skipped"
        warnings_text = "; ".join(result.warnings) if result.warnings else "None"
        response_panel = Panel(
            f"[bold]Resume:[/] {len(result.resume_text)} chars\n"
            f"[bold]Cover Letter:[/] {cov_letter_text}\n"
            f"[bold]Matched Skills:[/] {', '.join(result.matched_skills[:10]) or 'None'}\n"
            f"[bold]Warnings:[/] {warnings_text}\n",
            border_style="green",
            title="Tailoring Complete",
        )
        console.print(response_panel)

    _run_async(_run())


@app.command()
def run(
    _ctx: typer.Context,
    continuous: bool = typer.Option(
        False,
        "--continuous",
        "-c",
        help="Run continuously on an interval.",
    ),
    interval: float = typer.Option(
        15.0,
        "--interval",
        "-i",
        help="Minutes between pipeline passes in continuous mode.",
        min=1.0,
        max=120.0,
    ),
) -> None:
    """Run the full pipeline: discover -> analyse -> stage.

    Executes job discovery, context analysis, and Application record creation
    for all unprocessed listings, then stages them for human review.
    """
    console.print(Panel.fit("[bold cyan]\U0001f680  GetAJob Pipeline[/]", border_style="cyan"))
    _check_settings()

    async def _run() -> None:
        from agents.orchestrator_agent import OrchestratorAgent
        from core.database import create_engine
        from core.event_bus import InMemoryEventBus
        from core.llm_client import get_llm_client

        engine = create_engine()
        event_bus = InMemoryEventBus()
        llm_client = get_llm_client()

        orchestrator = OrchestratorAgent(
            engine=engine,
            llm_client=llm_client,
            event_bus=event_bus,
        )

        await orchestrator.start()
        try:
            if continuous:
                console.print(
                    "[blue]\u27f3[/] Continuous mode -- press Ctrl+C to stop gracefully.\n"
                )
                import asyncio

                interval_seconds = interval * 60.0
                while True:
                    result = await orchestrator.run_once()
                    _print_result_table(result, title="Pipeline Pass Complete")
                    console.print(f"[dim]Sleeping {interval:.0f} min until next pass...[/]\n")
                    await asyncio.sleep(interval_seconds)
            else:
                with Progress(
                    SpinnerColumn(),
                    TextColumn("[progress.description]{task.description}"),
                    console=console,
                    transient=True,
                ) as progress:
                    progress.add_task(description="Running pipeline...", total=None)
                    result = await orchestrator.run_once()

                _print_result_table(result, title="Pipeline Results")
        finally:
            await orchestrator.stop()

    _run_async(_run())


@app.command()
def serve(
    host: str = typer.Option(
        "127.0.0.1",
        "--host",
        help="Bind address for the web server.",
    ),
    port: int = typer.Option(
        8080,
        "--port",
        "-p",
        help="Port for the web server.",
        min=1024,
        max=65535,
    ),
) -> None:
    """Start the approval queue web UI.

    Launches a Uvicorn server serving the FastAPI approval queue app.
    The web UI provides a dashboard for reviewing applications, approving
    or rejecting submissions, and monitoring application state.
    """
    _check_settings()

    console.print(
        Panel.fit("[bold magenta]\U0001f310  Approval Queue Web UI[/]", border_style="magenta")
    )
    console.print(f"\n  Starting server at [bold]http://{host}:{port}[/]\n")

    from core.config import get_settings

    settings = get_settings()
    import uvicorn

    uvicorn.run(
        "approval_queue.main:app",
        host=host,
        port=port,
        reload=settings.environment == "development",
        log_level="debug" if settings.debug else "info",
        proxy_headers=True,
    )


@app.command()
def doctor() -> None:
    """Run a comprehensive pre-flight check and report system health.

    Verifies Python version, LLM configuration, database connectivity,
    config files, browser dependencies, data directories, and optional
    tooling (Docker).  Outputs a Rich table with status indicators and
    a summary panel.
    """
    console.print(
        Panel.fit(
            "[bold blue]\U0001fa7a  GetAJob Doctor - Pre-Flight Check[/]",
            border_style="blue",
        )
    )

    async def _run() -> None:
        import importlib.util
        import shutil

        from core.config import get_settings
        from core.database import create_engine

        checks: list[tuple[str, str, str]] = []
        critical_fail = False
        settings = None

        # 1. Python version.
        v = sys.version_info
        if v >= (3, 12):
            checks.append((
                "Python Version",
                "\u2705",
                f"Python {sys.version.split()[0]} (\u2265 3.12)",
            ))
        else:
            checks.append((
                "Python Version",
                "\u274c",
                f"Python {sys.version.split()[0]} (< 3.12 required)",
            ))
            critical_fail = True

        # 2. LLM API key.
        try:
            settings = get_settings()
            provider = settings.llm.provider or "unknown"
            api_key = settings.llm.api_key or os.environ.get("ANTHROPIC_API_KEY", "")
            if api_key:
                checks.append((
                    "LLM API Key",
                    "\u2705",
                    f"Provider: {provider}, Key starts with: {api_key[:8]}...",
                ))
            else:
                checks.append((
                    "LLM API Key",
                    "\u274c",
                    "No API key found (check GETAJOB_LLM__API_KEY or ANTHROPIC_API_KEY)",
                ))
                critical_fail = True
        except Exception as exc:
            checks.append(("LLM API Key", "\u274c", f"Config error: {exc}"))
            critical_fail = True

        # 3. Database connectivity.
        if settings is not None:
            try:
                db = settings.database
                from sqlalchemy import text

                async def _probe_db() -> None:
                    engine = create_engine()
                    try:
                        async with engine.connect() as conn:
                            await conn.execute(text("SELECT 1"))
                    finally:
                        await engine.dispose()

                try:
                    import asyncio

                    await asyncio.wait_for(_probe_db(), timeout=5.0)
                    checks.append((
                        "Database",
                        "\u2705",
                        f"Connected: {db.host}:{db.port}/{db.database}",
                    ))
                except TimeoutError:
                    checks.append((
                        "Database",
                        "\u274c",
                        f"Timed out after 5s: {db.host}:{db.port}/{db.database}",
                    ))
                    critical_fail = True
                except Exception as exc:
                    checks.append(("Database", "\u274c", f"Connection failed: {exc}"))
                    critical_fail = True
            except Exception as exc:
                checks.append(("Database", "\u274c", f"Config error: {exc}"))
                critical_fail = True

        # 4. Config files.
        project_root = Path(__file__).resolve().parent.parent.parent
        env_ok = (project_root / ".env").exists()
        yaml_ok = (project_root / "config" / "settings.yaml").exists()
        tpl_ok = (project_root / "env.template").exists()

        check_env = "\u2705" if env_ok else "\u274c"
        check_yaml = "\u2705" if yaml_ok else "\u274c"
        check_tpl = "\u2705" if tpl_ok else "\u274c"
        parts = [
            f"{check_env} .env",
            f"{check_yaml} config/settings.yaml",
            f"{check_tpl} env.template",
        ]
        checks.append(("Config Files", "\u2705" if env_ok else "\u26a0", "  ".join(parts)))

        # 5. Browser (Playwright).
        playwright_ok = importlib.util.find_spec("playwright") is not None

        if playwright_ok:
            checks.append(("Browser (Playwright)", "\u2705", "Playwright is installed"))
        else:
            checks.append((
                "Browser (Playwright)",
                "\u274c",
                "Not installed - run: playwright install chromium",
            ))

        # 6. Data directories.
        data_dir = settings.data_dir if settings else Path.cwd() / "data"
        existing: list[str] = []
        missing: list[str] = []

        def _check_dir(path: Path, label: str) -> None:
            (existing if path.exists() else missing).append(label)

        _check_dir(data_dir, "data")
        _check_dir(data_dir / "profiles", "data/profiles")
        _check_dir(data_dir / "resumes", "data/resumes")
        _check_dir(data_dir / "cover_letters", "data/cover_letters")

        if missing:
            detail = " ".join(f"\u2705 {d}" for d in existing)
            detail += " | Missing: " + " ".join(f"\u274c {d}" for d in missing)
            checks.append(("Data Directories", "\u26a0", detail))
        else:
            detail = " ".join(f"\u2705 {d}" for d in existing)
            checks.append(("Data Directories", "\u2705", detail))

        # 7. Docker (optional).
        docker_path = shutil.which("docker")
        if docker_path:
            checks.append(("Docker", "\u2705", f"Found: {docker_path}"))
        else:
            checks.append(("Docker", "-", "Not found (optional)"))

        # Render table.
        from rich.table import Table

        table = Table(title="System Health", border_style="blue")
        table.add_column("Check", style="cyan", no_wrap=True)
        table.add_column("Status", justify="center")
        table.add_column("Detail")

        status_colors = {
            "\u2705": "[green]\u2705[/]",
            "\u274c": "[red]\u274c[/]",
            "\u26a0": "[yellow]\u26a0[/]",
            "-": "[dim]-[/]",
        }
        for name, status, detail in checks:
            table.add_row(name, status_colors.get(status, status), detail)

        console.print()
        console.print(table)
        console.print()

        # Summary panel.
        if critical_fail:
            console.print(
                Panel(
                    "[bold red]\u2717  Some critical checks failed.[/]\n\n"
                    "  Run [cyan]getajob init[/] to set up your configuration.",
                    border_style="red",
                    title="Doctor Summary",
                )
            )
        elif any(s in ("\u26a0", "\u274c") for _, s, _ in checks if s != "-"):
            console.print(
                Panel(
                    "[bold yellow]\u26a0  All critical checks passed, but some items need attention.[/]",
                    border_style="yellow",
                    title="Doctor Summary",
                )
            )
        else:
            console.print(
                Panel(
                    "[bold green]\u2713  All checks passed![/]  Your system is ready to run GetAJob.",
                    border_style="green",
                    title="Doctor Summary",
                )
            )

    _run_async(_run())


@app.command()
def setup(
    drop_first: bool = typer.Option(
        False,
        "--drop-first",
        help="Drop existing tables before creating (destructive!).",
    ),
) -> None:
    """First-time setup -- create database tables and initialise the schema.

    Uses :func:`~core.database.run_migrations` to create all ORM tables.
    In production, use Alembic migrations instead of this command.

    After tables are created, ensures required data directories exist and
    prints a summary of what was set up.
    """
    console.print(
        Panel.fit("[bold yellow]\u2699\ufe0f  First-Time Setup[/]", border_style="yellow")
    )

    async def _run() -> None:
        from core.config import get_settings
        from core.database import create_engine, run_migrations

        engine = create_engine()
        try:
            # Database.
            console.print("  Creating database tables...")
            await run_migrations(engine, drop_first=drop_first)
            console.print("  [green]\u2713[/] Database schema ready.")

            # Data directories.
            settings = get_settings()
            data_dir = settings.data_dir
            data_dir.mkdir(parents=True, exist_ok=True)
            console.print(f"  [green]\u2713[/] Data directory: {data_dir}")

            # Additional subdirectories.
            for sub in ("profiles", "resumes", "cover_letters", "screenshots"):
                (data_dir / sub).mkdir(parents=True, exist_ok=True)
            console.print("  [green]\u2713[/] Data subdirectories created.")

            # Check for .env file.
            env_path = Path.cwd() / ".env"
            if env_path.exists():
                console.print(f"  [green]\u2713[/] Environment file found: {env_path}")
            else:
                env_template = Path.cwd() / "env.template"
                if env_template.exists():
                    console.print(
                        "  [yellow]\u26a0[/] No .env file found. "
                        "Copy env.template to .env and configure it:\n"
                        "       cp env.template .env"
                    )
                else:
                    console.print(
                        "  [yellow]\u26a0[/] No .env file found. Create one with your configuration."
                    )

            # Summary.
            console.print()
            console.print(
                Panel(
                    "[green]\u2713[/] Setup complete!\n\n"
                    "  [bold]Next steps:[/]\n"
                    "  1. Configure [cyan].env[/] with your API keys\n"
                    "  2. Run [cyan]getajob run[/] to start discovering jobs\n"
                    "  3. Run [cyan]getajob serve[/] to open the approval queue\n",
                    border_style="green",
                    title="Setup Complete",
                )
            )

        except Exception as exc:
            err_console.print(f"[red]\u2717[/] Setup failed: {exc}")
            raise typer.Exit(code=1) from exc
        finally:
            await engine.dispose()

    _run_async(_run())
