"""CLI commands for GetAJob.

Every function decorated with ``@app.command()``, ``@profile_app.command()``,
or ``@vector_app.command()`` lives here so the app registry in
``__init__.py`` stays clean.
"""

from __future__ import annotations as _annotations

import asyncio
import os
import sys
from pathlib import Path
from typing import Any

import structlog
import typer
import yaml
from rich.panel import Panel
from rich.progress import (
    Progress,
    SpinnerColumn,
    TextColumn,
)
from rich.table import Table

from agents.orchestrator_agent import OrchestratorAgent
from core.config import get_settings
from core.database import create_engine, run_migrations
from core.event_bus import InMemoryEventBus
from core.llm_client import get_llm_client
from getajob.cli import app, profile_app, vector_app
from getajob.cli._helpers import (
    _check_settings,
    _print_result_table,
    _run_async,
    _write_default_search_vectors,
    console,
    err_console,
)

logger = structlog.get_logger(__name__)

# ═══════════════════════════════════════════════════════════════════════════════
# init  —  First-run wizard
# ═══════════════════════════════════════════════════════════════════════════════


@app.command()
def init(
    force: bool = typer.Option(
        False,
        "--force",
        "-f",
        help="Overwrite existing .env without prompting.",
    ),
) -> None:
    """Interactive first-run wizard for non-technical users.

    Walks through the initial configuration: LLM API key, profile creation,
    default search vectors, and database setup -- all in one step.
    """
    console.print(
        Panel.fit(
            "[bold green]\U0001f680  GetAJob -- First-Run Init[/]",
            border_style="green",
        )
    )

    project_root = Path(__file__).resolve().parent.parent.parent
    env_path = project_root / ".env"

    # -- Step 1: Check for existing .env -----------------------------------
    if env_path.exists() and not force:
        overwrite = typer.confirm(
            f"  {env_path} already exists.\n  Overwrite existing configuration?",
            default=False,
        )
        if not overwrite:
            console.print("[yellow]  Init cancelled -- no changes made.[/]")
            raise typer.Exit()

    # -- Step 2: LLM provider & API key ------------------------------------
    console.print("\n[bold]\U0001f916  LLM Configuration[/]")

    existing_key = os.environ.get("GETAJOB_LLM__API_KEY")
    if existing_key:
        api_key = existing_key
        provider = os.environ.get("GETAJOB_LLM__PROVIDER", "anthropic")
        console.print("  [dim]Using GETAJOB_LLM__API_KEY from environment[/]")
    else:
        provider = typer.prompt("  LLM provider", default="anthropic")
        api_key = typer.prompt("  API key", hide_input=True)

    # -- Step 3: Write .env file -------------------------------------------
    model = "claude-sonnet-4-6" if provider.lower() in ("anthropic", "claude") else "gpt-4o"
    encryption_key = os.urandom(32).hex()
    encryption_salt = os.urandom(16).hex()
    tokenizer_salt = os.urandom(16).hex()

    env_content = f"""# GetAJob -- Environment Configuration
# Auto-generated by `getajob init`

GETAJOB_ENVIRONMENT=development
GETAJOB_DEBUG=true
GETAJOB_LOG_FORMAT=console

# -- PostgreSQL ----------------------------------------------------------------
GETAJOB_DATABASE__HOST=localhost
GETAJOB_DATABASE__PORT=5432
GETAJOB_DATABASE__DATABASE=getajob
GETAJOB_DATABASE__USER=getajob
GETAJOB_DATABASE__PASSWORD=change_me_in_production
GETAJOB_DATABASE__MIN_CONNECTIONS=2
GETAJOB_DATABASE__MAX_CONNECTIONS=10

# -- LLM -----------------------------------------------------------------------
GETAJOB_LLM__PROVIDER={provider}
GETAJOB_LLM__API_KEY={api_key if not existing_key else ""}
GETAJOB_LLM__MODEL={model}
GETAJOB_LLM__MAX_TOKENS=4096
GETAJOB_LLM__TEMPERATURE=0.7
GETAJOB_LLM__TIMEOUT_SECONDS=120

# -- Redis ---------------------------------------------------------------------
GETAJOB_REDIS__HOST=localhost
GETAJOB_REDIS__PORT=6379
GETAJOB_REDIS__DB=0

# -- Security / Encryption (auto-generated) ------------------------------------
GETAJOB_SECURITY__ENCRYPTION_KEY={encryption_key}
GETAJOB_SECURITY__ENCRYPTION_SALT={encryption_salt}
GETAJOB_SECURITY__TOKENIZER_SALT={tokenizer_salt}
# GETAJOB_SECURITY__APPROVAL_PASSWORD=

# -- Browser Automation --------------------------------------------------------
GETAJOB_BROWSER__HEADLESS=true
GETAJOB_BROWSER__VIEWPORT_WIDTH=1920
GETAJOB_BROWSER__VIEWPORT_HEIGHT=1080
GETAJOB_BROWSER__LOCALE=en-US
GETAJOB_BROWSER__SLOW_MO_MS=50
GETAJOB_BROWSER__NAVIGATION_TIMEOUT_SECONDS=30

# -- Job Discovery -------------------------------------------------------------
GETAJOB_JOB_DISCOVERY__MAX_APPLICATIONS_PER_DAY=50
"""
    env_path.write_text(env_content)
    env_path.chmod(0o600)
    console.print(f"  [green]\u2713[/] Configuration written: {env_path}")

    # -- Step 4: User profile (optional) -----------------------------------
    console.print("\n[bold]\U0001f464  User Profile (optional)[/]")
    console.print("  Provide your name and email to create a profile.")
    name = typer.prompt("  Name", default="")
    email = typer.prompt("  Email", default="")
    has_profile = bool(name and email)

    # -- Steps 5-7: Async operations ---------------------------------------
    async def _run_init() -> None:
        import core.config as core_config

        core_config._settings = None

        if has_profile:
            try:
                from core.schemas import ProfileCreate
                from profile_engine.profile_store import ProfileStore

                engine = create_engine()
                store = ProfileStore(engine)
                profile = await store.create_profile(
                    ProfileCreate(
                        name=name,
                        email=email,
                        phone="",
                    )
                )
                console.print(
                    f"  [green]\u2713[/] Profile created: [bold]{profile.name}[/] (id: {profile.id})"
                )
                await engine.dispose()
            except Exception as exc:
                console.print(f"  [yellow]\u26a0[/] Could not create profile: {exc}")
                console.print("    You can create one later by creating a profile directly.")

        try:
            _write_default_search_vectors(project_root)
            console.print("  [green]\u2713[/] Default search vectors written to settings.yaml")
        except Exception as exc:
            console.print(f"  [yellow]\u26a0[/] Could not write search vectors: {exc}")

        try:
            s = get_settings()
            engine = create_engine()
            await run_migrations(engine)

            data_dir = s.data_dir
            data_dir.mkdir(parents=True, exist_ok=True)
            for sub in ("profiles", "resumes", "cover_letters", "screenshots"):
                (data_dir / sub).mkdir(parents=True, exist_ok=True)

            console.print("  [green]\u2713[/] Database schema ready.")
            await engine.dispose()
        except Exception as exc:
            console.print(f"  [yellow]\u26a0[/] Could not initialise database: {exc}")
            console.print(
                "    Ensure PostgreSQL is running and .env is configured correctly."
            )

    _run_async(_run_init())

    # -- Step 8: Success summary -------------------------------------------
    console.print()
    console.print(
        Panel(
            "[bold green]\u2713[/]  GetAJob initialised successfully!\n\n"
            "  [bold]Next steps:[/]\n"
            "  \u2022 Run [cyan]getajob run[/]        "
            "-- Start discovering jobs\n"
            "  \u2022 Run [cyan]getajob serve[/]      "
            "-- Open the approval queue\n"
            "  \u2022 Edit [cyan].env[/]              "
            "-- Advanced configuration\n"
            "  \u2022 See [cyan]env.template[/]       "
            "-- All available settings\n",
            border_style="green",
            title="Init Complete",
        )
    )


# ═══════════════════════════════════════════════════════════════════════════════
# discover  —  Job discovery only
# ═══════════════════════════════════════════════════════════════════════════════


@app.command()
def discover(
    _ctx: typer.Context,
    continuous: bool = typer.Option(
        False,
        "--continuous",
        "-c",
        help="Run discovery continuously on an interval.",
    ),
    interval: float = typer.Option(
        15.0,
        "--interval",
        "-i",
        help="Minutes between discovery passes in continuous mode.",
        min=1.0,
        max=120.0,
    ),
) -> None:
    """Discover job listings from all configured search vectors.

    Executes the orchestrator's discovery phase: loads search vectors from
    config, queries each job source for new listings, runs context analysis
    against the active profile, and creates Application records in DISCOVERED
    state.
    """
    console.print(Panel.fit("[bold blue]\U0001f50d  Job Discovery[/]", border_style="blue"))
    _check_settings()

    async def _run() -> None:
        engine = create_engine()
        event_bus = InMemoryEventBus()
        llm_client = get_llm_client()

        orchestrator = OrchestratorAgent(
            engine=engine,
            llm_client=llm_client,
            event_bus=event_bus,
        )

        await orchestrator.start()
        try:
            if continuous:
                console.print(
                    "[blue]\u27f3[/] Continuous discovery mode -- press Ctrl+C to stop gracefully.\n"
                )
                interval_seconds = interval * 60.0
                while True:
                    result = await orchestrator.run_once()
                    _print_result_table(result, title="Discovery Pass Complete")
                    console.print(f"[dim]Sleeping {interval:.0f} min until next pass...[/]\n")
                    await asyncio.sleep(interval_seconds)
            else:
                with Progress(
                    SpinnerColumn(),
                    TextColumn("[progress.description]{task.description}"),
                    console=console,
                    transient=True,
                ) as progress:
                    progress.add_task(description="Discovering jobs...", total=None)
                    result = await orchestrator.run_once()

                _print_result_table(result, title="Discovery Results")
        finally:
            await orchestrator.stop()

    _run_async(_run())


# ═══════════════════════════════════════════════════════════════════════════════
# tailor  —  Tailor materials for a specific job
# ═══════════════════════════════════════════════════════════════════════════════


@app.command()
def tailor(
    _ctx: typer.Context,
    job_id: str = typer.Argument(
        ...,
        help="UUID of the job listing to tailor.",
    ),
) -> None:
    """Generate tailored resume and cover letter for a specific job.

    Runs the full analysis + tailoring pipeline for a single job listing
    that has already been discovered.
    """
    console.print(Panel.fit("[bold green]\U0001f4dd  Job Tailoring[/]", border_style="green"))
    _check_settings()

    async def _run() -> None:
        from sqlalchemy import select

        from core.database import get_session
        from core.models import JobListing

        engine = create_engine()
        event_bus = InMemoryEventBus()
        llm_client = get_llm_client()

        from agents.context_agent import ContextAgent
        from agents.tailoring_agent import TailoringAgent

        async with get_session(engine) as session:
            stmt = select(JobListing).where(JobListing.id == job_id)
            listing = (await session.execute(stmt)).scalar_one_or_none()

        if listing is None:
            err_console.print(f"[red]\u2717[/] Job listing '{job_id}' not found.")
            raise typer.Exit(code=1)

        rich_format = Panel(
            f"[bold]{listing.title}[/]\n"
            f"  Company: {listing.company}\n"
            f"  Source:  {listing.source}\n"
            f"  URL:     {listing.url or 'N/A'}",
            border_style="green",
            title="Job Details",
        )
        console.print(rich_format)

        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            console=console,
            transient=True,
        ) as progress:
            progress.add_task(description="Analysing job requirements...", total=None)
            context_agent = ContextAgent(
                engine=engine,
                llm_client=llm_client,
                event_bus=event_bus,
            )
            await context_agent.start()
            desc_text = listing.description_json.get("raw", "") if listing.description_json else ""
            analysis = await context_agent.analyze(
                job_id=str(listing.id),
                job_description=desc_text,
            )
            await context_agent.stop()

            console.print(f"\n  Match score: [bold]{analysis.match_score:.1%}[/]")
            if analysis.matching_skills:
                console.print(f"  Matching skills: {', '.join(analysis.matching_skills[:10])}")
            if analysis.missing_skills:
                console.print(
                    f"  [yellow]Missing skills: {', '.join(analysis.missing_skills[:5])}[/]"
                )
            if analysis.warnings:
                for w in analysis.warnings:
                    console.print(f"  [yellow]\u26a0 {w}[/]")
            console.print()

            progress.add_task(description="Generating resume & cover letter...", total=None)
            tailoring_agent = TailoringAgent(
                engine=engine,
                llm_client=llm_client,
                event_bus=event_bus,
            )
            await tailoring_agent.start()
            result = await tailoring_agent.tailor(
                job_listing_id=str(listing.id),
                profile_id=analysis.profile_id,
                job_title=listing.title,
                company=listing.company,
                job_description=desc_text,
                generate_cover_letter=True,
            )
            await tailoring_agent.stop()

        cover_letter_status = "\u2713 Generated" if result.cover_letter else "\u2717 Skipped"
        warnings_text = "; ".join(result.warnings) if result.warnings else "None"
        response_panel = Panel(
            f"[bold]Resume:[/] {len(result.resume_text)} chars\n"
            f"[bold]Cover Letter:[/] {cover_letter_status}\n"
            f"[bold]Matched Skills:[/] {', '.join(result.matched_skills[:10]) or 'None'}\n"
            f"[bold]Warnings:[/] {warnings_text}\n",
            border_style="green",
            title="Tailoring Complete",
        )
        console.print(response_panel)

    _run_async(_run())


# ═══════════════════════════════════════════════════════════════════════════════
# run  —  Full pipeline
# ═══════════════════════════════════════════════════════════════════════════════


@app.command()
def run(
    _ctx: typer.Context,
    continuous: bool = typer.Option(
        False,
        "--continuous",
        "-c",
        help="Run continuously on an interval.",
    ),
    interval: float = typer.Option(
        15.0,
        "--interval",
        "-i",
        help="Minutes between pipeline passes in continuous mode.",
        min=1.0,
        max=120.0,
    ),
) -> None:
    """Run the full pipeline: discover -> analyse -> stage.

    Executes job discovery, context analysis, and Application record creation
    for all unprocessed listings, then stages them for human review.
    """
    console.print(Panel.fit("[bold cyan]\U0001f680  GetAJob Pipeline[/]", border_style="cyan"))
    _check_settings()

    async def _run() -> None:
        engine = create_engine()
        event_bus = InMemoryEventBus()
        llm_client = get_llm_client()

        orchestrator = OrchestratorAgent(
            engine=engine,
            llm_client=llm_client,
            event_bus=event_bus,
        )

        await orchestrator.start()
        try:
            if continuous:
                console.print("[blue]\u27f3[/] Continuous mode -- press Ctrl+C to stop gracefully.\n")
                interval_seconds = interval * 60.0
                while True:
                    result = await orchestrator.run_once()
                    _print_result_table(result, title="Pipeline Pass Complete")
                    console.print(f"[dim]Sleeping {interval:.0f} min until next pass...[/]\n")
                    await asyncio.sleep(interval_seconds)
            else:
                with Progress(
                    SpinnerColumn(),
                    TextColumn("[progress.description]{task.description}"),
                    console=console,
                    transient=True,
                ) as progress:
                    progress.add_task(description="Running pipeline...", total=None)
                    result = await orchestrator.run_once()

                _print_result_table(result, title="Pipeline Results")
        finally:
            await orchestrator.stop()

    _run_async(_run())

# ═══════════════════════════════════════════════════════════════════════════════
# serve  —  Approval queue web UI
# ═══════════════════════════════════════════════════════════════════════════════


@app.command()
def serve(
    host: str = typer.Option(
        "127.0.0.1",
        "--host",
        help="Bind address for the web server.",
    ),
    port: int = typer.Option(
        8080,
        "--port",
        "-p",
        help="Port for the web server.",
        min=1024,
        max=65535,
    ),
) -> None:
    """Start the approval queue web UI.

    Launches a Uvicorn server serving the FastAPI approval queue app.
    """
    _check_settings()

    console.print(Panel.fit("[bold magenta]\U0001f310  Approval Queue Web UI[/]", border_style="magenta"))
    console.print(f"\n  Starting server at [bold]http://{host}:{port}[/]\n")

    settings = get_settings()
    import uvicorn

    uvicorn.run(
        "approval_queue.main:app",
        host=host,
        port=port,
        reload=settings.environment == "development",
        log_level="debug" if settings.debug else "info",
        proxy_headers=True,
    )


# ═══════════════════════════════════════════════════════════════════════════════
# doctor  —  Pre-flight check
# ═══════════════════════════════════════════════════════════════════════════════


@app.command()
def doctor() -> None:
    """Run a comprehensive pre-flight check and report system health."""
    console.print(Panel.fit("[bold blue]\U0001fa7a  GetAJob Doctor - Pre-Flight Check[/]", border_style="blue"))

    async def _run_doctor() -> None:
        checks: list[tuple[str, str, str]] = []
        critical_fail = False
        settings_obj = None

        v = sys.version_info
        if v >= (3, 12):
            checks.append(("Python Version", "\u2705", f"Python {sys.version.split()[0]}"))
        else:
            checks.append(("Python Version", "\u274c", f"Python {sys.version.split()[0]} (< 3.12)"))
            critical_fail = True

        try:
            settings_obj = get_settings()
            api_key = settings_obj.llm.api_key or os.environ.get("ANTHROPIC_API_KEY", "")
            if api_key:
                checks.append(("LLM API Key", "\u2705", f"Provider: {settings_obj.llm.provider}"))
            else:
                checks.append(("LLM API Key", "\u274c", "No API key found"))
                critical_fail = True
        except Exception as exc:
            checks.append(("LLM API Key", "\u274c", f"Config error: {exc}"))
            critical_fail = True

        if settings_obj is not None:
            try:
                from sqlalchemy import text
                async def _probe_db() -> None:
                    engine = create_engine()
                    try:
                        async with engine.connect() as conn:
                            await conn.execute(text("SELECT 1"))
                    finally:
                        await engine.dispose()
                try:
                    await asyncio.wait_for(_probe_db(), timeout=5.0)
                    db = settings_obj.database
                    checks.append(("Database", "\u2705", f"Connected: {db.host}:{db.port}"))
                except TimeoutError:
                    checks.append(("Database", "\u274c", "Timed out after 5s"))
                    critical_fail = True
                except Exception as exc:
                    checks.append(("Database", "\u274c", f"Failed: {exc}"))
                    critical_fail = True
            except Exception as exc:
                checks.append(("Database", "\u274c", f"Config error: {exc}"))
                critical_fail = True

        project_root = Path(__file__).resolve().parent.parent.parent
        env_ok = (project_root / ".env").exists()
        yaml_ok = (project_root / "config" / "settings.yaml").exists()
        checks.append((
            "Config Files",
            "\u2705" if env_ok else "\u26a0",
            f"{'E' if env_ok else 'M'} .env  {'Y' if yaml_ok else 'M'} settings.yaml",
        ))

        import importlib.util
        checks.append(("Browser", "\u2705" if importlib.util.find_spec("playwright") else "\u274c",
                       "Playwright installed" if importlib.util.find_spec("playwright") else "Not installed"))

        data_dir = settings_obj.data_dir if settings_obj else Path.cwd() / "data"
        missing_dirs = [d for d in ("data", "data/profiles", "data/resumes", "data/cover_letters")
                        if not (data_dir / d if d != "data" else data_dir).exists()
                       ] if settings_obj else []
        checks.append(("Data Dirs", "\u2705" if not missing_dirs else "\u26a0",
                       "All present" if not missing_dirs else f"Missing: {', '.join(missing_dirs)}"))

        import shutil
        checks.append(("Docker", "\u2705" if shutil.which("docker") else "-",
                       "Found" if shutil.which("docker") else "Not found (optional)"))

        table = Table(title="System Health", border_style="blue")
        table.add_column("Check", style="cyan", no_wrap=True)
        table.add_column("Status", justify="center")
        table.add_column("Detail")

        status_colors = {"\u2705": "[green]\u2705[/]", "\u274c": "[red]\u274c[/]",
                         "\u26a0": "[yellow]\u26a0[/]", "-": "[dim]-[/]"}
        for name, status, detail in checks:
            table.add_row(name, status_colors.get(status, status), detail)
        console.print()
        console.print(table)
        console.print()

        if critical_fail:
            console.print(Panel("[bold red]\u2717  Some critical checks failed.[/]\n\n"
                                "  Run [cyan]getajob init[/] to set up your configuration.",
                                border_style="red", title="Doctor Summary"))
        elif any(s in ("\u26a0", "\u274c") for _, s, _ in checks if s != "-"):
            console.print(Panel("[bold yellow]\u26a0  All critical checks passed, but some items need attention.[/]",
                                border_style="yellow", title="Doctor Summary"))
        else:
            console.print(Panel("[bold green]\u2713  All checks passed![/]  Your system is ready.",
                                border_style="green", title="Doctor Summary"))

    _run_async(_run_doctor())


# ═══════════════════════════════════════════════════════════════════════════════
# setup  —  First-time database setup
# ═══════════════════════════════════════════════════════════════════════════════


@app.command()
def setup(
    drop_first: bool = typer.Option(
        False,
        "--drop-first",
        help="Drop existing tables before creating (destructive!).",
    ),
) -> None:
    """First-time setup -- create database tables and initialise the schema."""
    console.print(Panel.fit("[bold yellow]\u2699\ufe0f  First-Time Setup[/]", border_style="yellow"))

    async def _run_setup() -> None:
        engine = create_engine()
        try:
            console.print("  Creating database tables...")
            await run_migrations(engine, drop_first=drop_first)
            console.print("  [green]\u2713[/] Database schema ready.")
            settings = get_settings()
            data_dir = settings.data_dir
            data_dir.mkdir(parents=True, exist_ok=True)
            console.print(f"  [green]\u2713[/] Data directory: {data_dir}")
            for sub in ("profiles", "resumes", "cover_letters", "screenshots"):
                (data_dir / sub).mkdir(parents=True, exist_ok=True)
            console.print("  [green]\u2713[/] Data subdirectories created.")
            console.print()
            console.print(Panel("[green]\u2713[/] Setup complete!\n\n"
                                "  [bold]Next steps:[/]\n"
                                "  1. Configure [cyan].env[/] with your API keys\n"
                                "  2. Run [cyan]getajob run[/] to start discovering jobs\n"
                                "  3. Run [cyan]getajob serve[/] to open the approval queue\n",
                                border_style="green", title="Setup Complete"))
        except Exception as exc:
            err_console.print(f"[red]\u2717[/] Setup failed: {exc}")
            raise typer.Exit(code=1) from exc
        finally:
            await engine.dispose()

    _run_async(_run_setup())


# ═══════════════════════════════════════════════════════════════════════════════
# Profile sub-app  —  show, update
# ═══════════════════════════════════════════════════════════════════════════════


@profile_app.command()
def show() -> None:
    """Show the currently active profile."""
    async def _run_show() -> None:
        engine = None
        try:
            from core.database import create_engine as _ce
            from profile_engine.profile_store import ProfileStore
            engine = _ce()
            store = ProfileStore(engine)
            profiles = await store.list_profiles(limit=1)
            if not profiles:
                console.print("[yellow]No profile configured. Run 'getajob init' to create one.[/]")
                return
            profile = profiles[0]
            table = Table(title="User Profile", border_style="blue")
            table.add_column("Field", style="cyan", no_wrap=True)
            table.add_column("Value")
            table.add_row("Name", profile.name or "")
            table.add_row("Email", profile.email or "")
            table.add_row("Location", profile.location or "[dim]not set[/]")
            skills_str = ", ".join(s.name for s in profile.skills) if profile.skills else "[dim]none[/]"
            table.add_row("Skills", skills_str)
            table.add_row("Work Authorization", profile.work_authorization or "[dim]not set[/]")
            console.print(table)
        except Exception as exc:
            err_console.print(f"[red]\u2717[/] Could not load profile: {exc}")
        finally:
            if engine is not None:
                await engine.dispose()
    _run_async(_run_show())


@profile_app.command()
def update() -> None:
    """Update profile fields via interactive prompts."""
    async def _run_update() -> None:
        engine = None
        try:
            from core.database import create_engine as _ce
            from core.schemas import ProfileUpdate, SkillSchema
            from profile_engine.profile_store import ProfileStore
            engine = _ce()
            store = ProfileStore(engine)
            profiles = await store.list_profiles(limit=1)
            if not profiles:
                console.print("[yellow]No profile configured. Run 'getajob init' to create one.[/]")
                return
            current = profiles[0]
            console.print(Panel.fit("[bold cyan]\u270f\ufe0f  Update Profile[/]", border_style="cyan"))
            console.print("[dim]Press Enter to keep the current value.[/]\n")
            name = typer.prompt("  Name", default=current.name or "")
            email = typer.prompt("  Email", default=current.email or "")
            location = typer.prompt("  Location", default=current.location or "")
            current_skills_str = ", ".join(s.name for s in current.skills) if current.skills else ""
            skills_str = typer.prompt("  Skills (comma-separated)", default=current_skills_str)
            work_auth = typer.prompt("  Work Authorization", default=current.work_authorization or "")
            update_data: dict[str, Any] = {}
            if name.strip() and name.strip() != (current.name or ""):
                update_data["name"] = name.strip()
            if email.strip() and email.strip() != (current.email or ""):
                update_data["email"] = email.strip()
            if location.strip() and location.strip() != (current.location or ""):
                update_data["location"] = location.strip()
            if skills_str.strip():
                new_skills = [s.strip() for s in skills_str.split(",") if s.strip()]
                old_skills = [s.name for s in current.skills] if current.skills else []
                if new_skills != old_skills:
                    update_data["skills"] = [SkillSchema(name=s) for s in new_skills]
            elif current.skills:
                update_data["skills"] = []
            if work_auth.strip() and work_auth.strip() != (current.work_authorization or ""):
                update_data["work_authorization"] = work_auth.strip()
            elif not work_auth.strip() and current.work_authorization:
                update_data["work_authorization"] = ""
            if not update_data:
                console.print("[yellow]No changes made.[/]")
                return
            await store.update_profile(current.id, ProfileUpdate(**update_data))
            console.print("\n[green]\u2713[/] Profile updated successfully.")
        except Exception as exc:
            err_console.print(f"[red]\u2717[/] Could not update profile: {exc}")
        finally:
            if engine is not None:
                await engine.dispose()
    _run_async(_run_update())


# ═══════════════════════════════════════════════════════════════════════════════
# Vector sub-app  —  list, add
# ═══════════════════════════════════════════════════════════════════════════════


@vector_app.command(name="list")
def vector_list() -> None:
    """List all configured search vectors from config/settings.yaml."""
    project_root = Path(__file__).resolve().parent.parent.parent
    yaml_path = project_root / "config" / "settings.yaml"

    if not yaml_path.exists():
        console.print("[yellow]No search vectors configured. Run 'getajob init' to set up defaults.[/]")
        raise typer.Exit()

    with yaml_path.open("r") as f:
        data = yaml.safe_load(f) or {}

    vectors = data.get("search_vectors", [])
    if not vectors:
        console.print("[yellow]No search vectors configured.[/]")
        raise typer.Exit()

    table = Table(title="Search Vectors", border_style="blue")
    table.add_column("Name", style="cyan", no_wrap=True)
    table.add_column("Keywords", style="green")
    table.add_column("Locations", style="yellow")
    table.add_column("Remote", justify="center")

    for vec in vectors:
        name = vec.get("name") or ", ".join(vec.get("roles", ["(unnamed)"])[:2])
        kw_list = vec.get("keywords", [])
        keywords = ", ".join(kw_list[:5])
        if len(kw_list) > 5:
            keywords += "\u2026"
        loc_list = vec.get("locations", [])
        locations = ", ".join(loc_list) if loc_list else "[dim]any[/]"
        is_remote = any(loc.strip().lower() == "remote" for loc in loc_list)
        remote_str = "[green]\u2713[/]" if is_remote else "[red]\u2717[/]"
        table.add_row(name, keywords, locations, remote_str)

    console.print(table)


@vector_app.command(name="add")
def vector_add() -> None:
    """Add a new search vector with interactive prompts."""
    project_root = Path(__file__).resolve().parent.parent.parent
    yaml_path = project_root / "config" / "settings.yaml"

    console.print(Panel.fit("[bold green]+  Add Search Vector[/]", border_style="green"))

    vec_name = typer.prompt("  Vector name")
    console.print("  [dim]e.g. 'Backend Engineer' or 'Frontend Developer'[/]")
    keywords_str = typer.prompt("  Keywords (comma-separated)")
    console.print("  [dim]e.g. python, go, kubernetes, aws[/]")
    location = typer.prompt("  Location (optional, press Enter to skip)", default="")
    remote = typer.confirm("  Remote only?", default=True)

    keywords = [k.strip() for k in keywords_str.split(",") if k.strip()]
    locations: list[str] = []
    if location.strip():
        locations.append(location.strip())
    if remote and "remote" not in [loc.strip().lower() for loc in locations]:
        locations.insert(0, "remote")

    new_vector: dict[str, Any] = {"name": vec_name, "keywords": keywords, "locations": locations}

    if yaml_path.exists():
        with yaml_path.open("r") as f:
            data: dict[str, Any] = yaml.safe_load(f) or {}
    else:
        data = {}

    vectors = data.setdefault("search_vectors", [])
    vectors.append(new_vector)

    with yaml_path.open("w") as f:
        yaml.safe_dump(data, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

    console.print()
    table = Table(border_style="green", show_header=False)
    table.add_column("Field", style="bold cyan")
    table.add_column("Value")
    table.add_row("Name", vec_name)
    table.add_row("Keywords", ", ".join(keywords))
    table.add_row("Locations", ", ".join(locations) if locations else "[dim]any[/]")
    table.add_row("Remote", "[green]Yes[/]" if remote else "[red]No[/]")
    console.print(table)
    console.print(f"\n[green]\u2713[/] Vector '[bold]{vec_name}[/]' added successfully.")
