"""Manual submission fallback when browser automation is unavailable.

The :func:`export_submit_url` function extracts the job listing URL from an
application record and returns it with a help-text message so the user can
navigate to the portal and submit manually.

This module has **zero dependencies on Playwright or browser_use** — it is
always safe to import, even when the browser toolchain is not installed.
"""

from __future__ import annotations as _annotations

from typing import Any

__all__: list[str] = [
    "export_submit_url",
]


def export_submit_url(application: Any) -> dict[str, Any]:
    """Return the job listing URL for manual browser submission.

    When browser automation is unavailable (Playwright / Chromium not
    installed), call this function to get the application's job listing
    URL and a help-text so the user can submit via their regular browser.

    Args:
        application: An ``Application`` ORM model (or any object whose
            ``.job_listing`` attribute exposes ``url``, ``company``, and
            ``title``).

    Returns:
        A dictionary with keys:

        - **url** — The job listing URL to open in a regular browser.
        - **company** — Name of the hiring company.
        - **title** — Job title.
        - **instructions** — Human-readable instructions for submitting
          manually.
    """
    listing = application.job_listing

    url = listing.url or ""
    company = listing.company or "Unknown Company"
    title = listing.title or "Unknown Position"

    return {
        "url": url,
        "company": company,
        "title": title,
        "instructions": (
            f"Browser automation is not available. Please submit your "
            f"application for **{title}** at **{company}** manually:\n\n"
            f"1. Open this URL in your browser:\n"
            f"   {url}\n\n"
            f"2. Upload your tailored resume (generated by GetAJob).\n"
            f"3. Fill in any remaining fields, paste your cover letter.\n"
            f"4. Review and submit the application.\n\n"
            f"After submitting, mark the application complete in the "
            f"GetAJob dashboard to continue tracking."
        ),
    }
