"""GetAJob CLI - command-line interface for the job application platform.

Usage
-----
    # Run the full pipeline (discover -> tailor -> stage)
    python -m getajob.cli run

    # Discover jobs only
    python -m getajob.cli discover

    # Tailor a specific job
    python -m getajob.cli tailor <job-id>

    # Start the approval queue web UI
    python -m getajob.cli serve

    # First-time setup (create tables, etc.)
    python -m getajob.cli setup
"""

from __future__ import annotations as _annotations

import asyncio
import os
import sys
from collections.abc import Coroutine
from pathlib import Path
from typing import Any

import structlog
import typer
import yaml
from rich.console import Console
from rich.panel import Panel
from rich.progress import (
    Progress,
    SpinnerColumn,
    TextColumn,
)
from rich.table import Table

from agents.orchestrator_agent import OrchestratorAgent
from core.config import get_settings
from core.database import create_engine, run_migrations
from core.event_bus import InMemoryEventBus
from core.llm_client import get_llm_client

__all__: list[str] = [
    "app",
]

# ── Logger ───────────────────────────────────────────────────────────────────

logger = structlog.get_logger(__name__)

# ── Typer app ────────────────────────────────────────────────────────────────

app = typer.Typer(
    name="getajob",
    help="GetAJob - automated job application platform",
    add_completion=False,
    pretty_exceptions_show_locals=False,
)

console = Console()
err_console = Console(stderr=True)

# ── Vector sub-app ───────────────────────────────────────────────────────────

vector_app = typer.Typer(
    name="vector",
    help="Manage search vectors.",
)

profile_app = typer.Typer(
    name="profile",
    help="Manage user profile.",
)


# ── Utility ──────────────────────────────────────────────────────────────────


def _version_callback(value: bool) -> None:
    if value:
        from getajob import __version__

        console.print(f"GetAJob v{__version__}")
        raise typer.Exit()


# ── Commands ─────────────────────────────────────────────────────────────────


@app.callback()
def _main(
    version: bool = typer.Option(
        False,
        "--version",
        "-V",
        help="Show version and exit.",
        callback=_version_callback,
        is_eager=True,
    ),
) -> None:
    """GetAJob -- automated, agentic job application platform for 2026."""
    pass


# ── Init (first-run wizard) ─────────────────────────────────────────────────


@app.command()
def init(
    force: bool = typer.Option(
        False,
        "--force",
        "-f",
        help="Overwrite existing .env without prompting.",
    ),
) -> None:
    """Interactive first-run wizard for non-technical users.

    Walks through the initial configuration: LLM API key, profile creation,
    default search vectors, and database setup -- all in one step.
    """
    console.print(
        Panel.fit(
            "[bold green]🚀  GetAJob -- First-Run Init[/]",
            border_style="green",
        )
    )

    project_root = Path(__file__).resolve().parent.parent
    env_path = project_root / ".env"

    # ── Step 1: Check for existing .env ──────────────────────────────────
    if env_path.exists() and not force:
        overwrite = typer.confirm(
            f"  {env_path} already exists.\n  Overwrite existing configuration?",
            default=False,
        )
        if not overwrite:
            console.print("[yellow]  Init cancelled -- no changes made.[/]")
            raise typer.Exit()

    # ── Step 2: LLM provider & API key ────────────────────────────────────
    console.print("\n[bold]🤖  LLM Configuration[/]")

    # ponytail: prefer env var over file storage for secrets
    existing_key = os.environ.get("GETAJOB_LLM__API_KEY")
    if existing_key:
        api_key = existing_key
        provider = os.environ.get("GETAJOB_LLM__PROVIDER", "anthropic")
        console.print("  [dim]Using GETAJOB_LLM__API_KEY from environment[/]")
    else:
        provider = typer.prompt("  LLM provider", default="anthropic")
        api_key = typer.prompt("  API key", hide_input=True)

    # ── Step 3: Write .env file ────────────────────────────────────────────
    model = "claude-sonnet-4-6" if provider.lower() in ("anthropic", "claude") else "gpt-4o"
    encryption_key = os.urandom(32).hex()
    encryption_salt = os.urandom(16).hex()
    tokenizer_salt = os.urandom(16).hex()

    env_content = f"""# GetAJob -- Environment Configuration
# Auto-generated by `getajob init`

GETAJOB_ENVIRONMENT=development
GETAJOB_DEBUG=true
GETAJOB_LOG_FORMAT=console

# -- PostgreSQL ----------------------------------------------------------------
GETAJOB_DATABASE__HOST=localhost
GETAJOB_DATABASE__PORT=5432
GETAJOB_DATABASE__DATABASE=getajob
GETAJOB_DATABASE__USER=getajob
GETAJOB_DATABASE__PASSWORD=change_me_in_production
GETAJOB_DATABASE__MIN_CONNECTIONS=2
GETAJOB_DATABASE__MAX_CONNECTIONS=10

# -- LLM -----------------------------------------------------------------------
GETAJOB_LLM__PROVIDER={provider}
GETAJOB_LLM__API_KEY={api_key if not existing_key else ""}
GETAJOB_LLM__MODEL={model}
GETAJOB_LLM__MAX_TOKENS=4096
GETAJOB_LLM__TEMPERATURE=0.7
GETAJOB_LLM__TIMEOUT_SECONDS=120

# -- Redis ---------------------------------------------------------------------
GETAJOB_REDIS__HOST=localhost
GETAJOB_REDIS__PORT=6379
GETAJOB_REDIS__DB=0

# -- Security / Encryption (auto-generated) ------------------------------------
GETAJOB_SECURITY__ENCRYPTION_KEY={encryption_key}
GETAJOB_SECURITY__ENCRYPTION_SALT={encryption_salt}
GETAJOB_SECURITY__TOKENIZER_SALT={tokenizer_salt}
# GETAJOB_SECURITY__APPROVAL_PASSWORD=

# -- Browser Automation --------------------------------------------------------
GETAJOB_BROWSER__HEADLESS=true
GETAJOB_BROWSER__VIEWPORT_WIDTH=1920
GETAJOB_BROWSER__VIEWPORT_HEIGHT=1080
GETAJOB_BROWSER__LOCALE=en-US
GETAJOB_BROWSER__SLOW_MO_MS=50
GETAJOB_BROWSER__NAVIGATION_TIMEOUT_SECONDS=30

# -- Job Discovery -------------------------------------------------------------
GETAJOB_JOB_DISCOVERY__MAX_APPLICATIONS_PER_DAY=50
"""
    env_path.write_text(env_content)
    env_path.chmod(0o600)
    console.print(f"  [green]✓[/] Configuration written: {env_path}")

    # ── Step 4: User profile (optional) ───────────────────────────────────
    console.print("\n[bold]👤  User Profile (optional)[/]")
    console.print("  Provide your name and email to create a profile.")
    name = typer.prompt("  Name", default="")
    email = typer.prompt("  Email", default="")
    has_profile = bool(name and email)

    # ── Steps 5-7: Async operations ───────────────────────────────────────
    async def _run_init() -> None:
        # Force settings reload now that .env exists on disk.
        import core.config as core_config

        core_config._settings = None

        # Step 5: Create user profile in the database.
        if has_profile:
            try:
                from core.schemas import ProfileCreate
                from profile_engine.profile_store import ProfileStore

                engine = create_engine()
                store = ProfileStore(engine)
                profile = await store.create_profile(
                    ProfileCreate(
                        name=name,
                        email=email,
                        phone="",
                    )
                )
                console.print(
                    f"  [green]✓[/] Profile created: [bold]{profile.name}[/] (id: {profile.id})"
                )
                await engine.dispose()
            except Exception as exc:
                console.print(f"  [yellow]⚠[/] Could not create profile: {exc}")
                console.print("    You can create one later by creating a profile directly.")

        # Step 6: Write default search vectors into settings.yaml.
        try:
            _write_default_search_vectors(project_root)
            console.print("  [green]✓[/] Default search vectors written to settings.yaml")
        except Exception as exc:
            console.print(f"  [yellow]⚠[/] Could not write search vectors: {exc}")

        # Step 7: Database setup (create tables + data directories).
        try:
            s = get_settings()
            engine = create_engine()
            await run_migrations(engine)

            data_dir = s.data_dir
            data_dir.mkdir(parents=True, exist_ok=True)
            for sub in ("profiles", "resumes", "cover_letters", "screenshots"):
                (data_dir / sub).mkdir(parents=True, exist_ok=True)

            console.print("  [green]✓[/] Database schema ready.")
            await engine.dispose()
        except Exception as exc:
            console.print(f"  [yellow]⚠[/] Could not initialise database: {exc}")
            console.print("    Ensure PostgreSQL is running and .env is configured correctly.")

    _run_async(_run_init())

    # ── Step 8: Success summary ───────────────────────────────────────────
    console.print()
    console.print(
        Panel(
            "[bold green]✓[/]  GetAJob initialised successfully!\n\n"
            "  [bold]Next steps:[/]\n"
            "  • Run [cyan]getajob run[/]        "
            "-- Start discovering jobs\n"
            "  • Run [cyan]getajob serve[/]      "
            "-- Open the approval queue\n"
            "  • Edit [cyan].env[/]              "
            "-- Advanced configuration\n"
            "  • See [cyan]env.template[/]       "
            "-- All available settings\n",
            border_style="green",
            title="Init Complete",
        )
    )


@app.command()
def discover(
    _ctx: typer.Context,
    continuous: bool = typer.Option(
        False,
        "--continuous",
        "-c",
        help="Run discovery continuously on an interval.",
    ),
    interval: float = typer.Option(
        15.0,
        "--interval",
        "-i",
        help="Minutes between discovery passes in continuous mode.",
        min=1.0,
        max=120.0,
    ),
) -> None:
    """Discover job listings from all configured search vectors.

    Executes the orchestrator's discovery phase: loads search vectors from
    config, queries each job source for new listings, runs context analysis
    against the active profile, and creates Application records in DISCOVERED
    state.
    """
    console.print(Panel.fit("[bold blue]🔍  Job Discovery[/]", border_style="blue"))
    _check_settings()

    async def _run() -> None:
        engine = create_engine()
        event_bus = InMemoryEventBus()
        llm_client = get_llm_client()

        orchestrator = OrchestratorAgent(
            engine=engine,
            llm_client=llm_client,
            event_bus=event_bus,
        )

        await orchestrator.start()
        try:
            if continuous:
                console.print(
                    "[blue]⟳[/] Continuous discovery mode -- press Ctrl+C to stop gracefully.\n"
                )
                interval_seconds = interval * 60.0
                while True:
                    result = await orchestrator.run_once()
                    _print_result_table(result, title="Discovery Pass Complete")
                    console.print(f"[dim]Sleeping {interval:.0f} min until next pass...[/]\n")
                    await asyncio.sleep(interval_seconds)
            else:
                with Progress(
                    SpinnerColumn(),
                    TextColumn("[progress.description]{task.description}"),
                    console=console,
                    transient=True,
                ) as progress:
                    progress.add_task(description="Discovering jobs...", total=None)
                    result = await orchestrator.run_once()

                _print_result_table(result, title="Discovery Results")
        finally:
            await orchestrator.stop()

    _run_async(_run())


@app.command()
def tailor(
    _ctx: typer.Context,
    job_id: str = typer.Argument(
        ...,
        help="UUID of the job listing to tailor.",
    ),
) -> None:
    """Generate tailored resume and cover letter for a specific job.

    Runs the full analysis + tailoring pipeline for a single job listing
    that has already been discovered.  Loads the job from the database,
    runs ContextAgent to extract requirements, then TailoringAgent to
    produce tailored materials.
    """
    console.print(Panel.fit("[bold green]📝  Job Tailoring[/]", border_style="green"))
    _check_settings()

    async def _run() -> None:
        from sqlalchemy import select

        from core.database import get_session
        from core.models import JobListing

        engine = create_engine()
        event_bus = InMemoryEventBus()
        llm_client = get_llm_client()

        from agents.context_agent import ContextAgent
        from agents.tailoring_agent import TailoringAgent

        # Load the listing.
        async with get_session(engine) as session:
            stmt = select(JobListing).where(JobListing.id == job_id)
            listing = (await session.execute(stmt)).scalar_one_or_none()

        if listing is None:
            err_console.print(f"[red]✗[/] Job listing '{job_id}' not found.")
            raise typer.Exit(code=1)

        rich_format = Panel(
            f"[bold]{listing.title}[/]\n"
            f"  Company: {listing.company}\n"
            f"  Source:  {listing.source}\n"
            f"  URL:     {listing.url or 'N/A'}",
            border_style="green",
            title="Job Details",
        )
        console.print(rich_format)

        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            console=console,
            transient=True,
        ) as progress:
            # Context analysis.
            progress.add_task(description="Analysing job requirements...", total=None)
            context_agent = ContextAgent(
                engine=engine,
                llm_client=llm_client,
                event_bus=event_bus,
            )
            await context_agent.start()
            desc_text = listing.description_json.get("raw", "") if listing.description_json else ""
            analysis = await context_agent.analyze(
                job_id=str(listing.id),
                job_description=desc_text,
            )
            await context_agent.stop()

            console.print(f"\n  Match score: [bold]{analysis.match_score:.1%}[/]")
            if analysis.matching_skills:
                console.print(f"  Matching skills: {', '.join(analysis.matching_skills[:10])}")
            if analysis.missing_skills:
                console.print(
                    f"  [yellow]Missing skills: {', '.join(analysis.missing_skills[:5])}[/]"
                )
            if analysis.warnings:
                for w in analysis.warnings:
                    console.print(f"  [yellow]⚠ {w}[/]")
            console.print()

            # Tailoring.
            progress.add_task(description="Generating resume & cover letter...", total=None)
            tailoring_agent = TailoringAgent(
                engine=engine,
                llm_client=llm_client,
                event_bus=event_bus,
            )
            await tailoring_agent.start()
            result = await tailoring_agent.tailor(
                job_listing_id=str(listing.id),
                profile_id=analysis.profile_id,
                job_title=listing.title,
                company=listing.company,
                job_description=desc_text,
                generate_cover_letter=True,
            )
            await tailoring_agent.stop()

        # Display results.
        response_panel = Panel(
            f"[bold]Resume:[/] {len(result.resume_text)} chars\n"
            f"[bold]Cover Letter:[/] {'✓ Generated' if result.cover_letter else '✗ Skipped'}\n"
            f"[bold]Matched Skills:[/] {', '.join(result.matched_skills[:10]) or 'None'}\n"
            f"[bold]Warnings:[/] {'; '.join(result.warnings) if result.warnings else 'None'}\n",
            border_style="green",
            title="Tailoring Complete",
        )
        console.print(response_panel)

    _run_async(_run())


@app.command()
def run(
    _ctx: typer.Context,
    continuous: bool = typer.Option(
        False,
        "--continuous",
        "-c",
        help="Run continuously on an interval.",
    ),
    interval: float = typer.Option(
        15.0,
        "--interval",
        "-i",
        help="Minutes between pipeline passes in continuous mode.",
        min=1.0,
        max=120.0,
    ),
) -> None:
    """Run the full pipeline: discover -> analyse -> stage.

    Executes job discovery, context analysis, and Application record creation
    for all unprocessed listings, then stages them for human review.
    """
    console.print(Panel.fit("[bold cyan]🚀  GetAJob Pipeline[/]", border_style="cyan"))
    _check_settings()

    async def _run() -> None:
        engine = create_engine()
        event_bus = InMemoryEventBus()
        llm_client = get_llm_client()

        orchestrator = OrchestratorAgent(
            engine=engine,
            llm_client=llm_client,
            event_bus=event_bus,
        )

        await orchestrator.start()
        try:
            if continuous:
                console.print("[blue]⟳[/] Continuous mode -- press Ctrl+C to stop gracefully.\n")
                interval_seconds = interval * 60.0
                while True:
                    result = await orchestrator.run_once()
                    _print_result_table(result, title="Pipeline Pass Complete")
                    console.print(f"[dim]Sleeping {interval:.0f} min until next pass...[/]\n")
                    await asyncio.sleep(interval_seconds)
            else:
                with Progress(
                    SpinnerColumn(),
                    TextColumn("[progress.description]{task.description}"),
                    console=console,
                    transient=True,
                ) as progress:
                    progress.add_task(description="Running pipeline...", total=None)
                    result = await orchestrator.run_once()

                _print_result_table(result, title="Pipeline Results")
        finally:
            await orchestrator.stop()

    _run_async(_run())


@app.command()
def serve(
    host: str = typer.Option(
        "127.0.0.1",
        "--host",
        help="Bind address for the web server.",
    ),
    port: int = typer.Option(
        8080,
        "--port",
        "-p",
        help="Port for the web server.",
        min=1024,
        max=65535,
    ),
) -> None:
    """Start the approval queue web UI.

    Launches a Uvicorn server serving the FastAPI approval queue app.
    The web UI provides a dashboard for reviewing applications, approving
    or rejecting submissions, and monitoring application state.
    """
    _check_settings()

    console.print(Panel.fit("[bold magenta]🌐  Approval Queue Web UI[/]", border_style="magenta"))
    console.print(f"\n  Starting server at [bold]http://{host}:{port}[/]\n")

    settings = get_settings()
    import uvicorn

    uvicorn.run(
        "approval_queue.main:app",
        host=host,
        port=port,
        reload=settings.environment == "development",
        log_level="debug" if settings.debug else "info",
        proxy_headers=True,
    )


@app.command()
def doctor() -> None:
    """Run a comprehensive pre-flight check and report system health.

    Verifies Python version, LLM configuration, database connectivity,
    config files, browser dependencies, data directories, and optional
    tooling (Docker).  Outputs a Rich table with status indicators and
    a summary panel.
    """
    console.print(
        Panel.fit(
            "[bold blue]🩺  GetAJob Doctor - Pre-Flight Check[/]",
            border_style="blue",
        )
    )

    async def _run() -> None:
        checks: list[tuple[str, str, str]] = []
        critical_fail = False
        settings = None

        # ── 1. Python version ────────────────────────────────────────────────
        v = sys.version_info
        if v >= (3, 12):
            checks.append((
                "Python Version",
                "✅",
                f"Python {sys.version.split()[0]} (≥ 3.12)",
            ))
        else:
            checks.append((
                "Python Version",
                "❌",
                f"Python {sys.version.split()[0]} (< 3.12 required)",
            ))
            critical_fail = True

        # ── 2. LLM API key ─────────────────────────────────────────────────
        try:
            settings = get_settings()
            provider = settings.llm.provider or "unknown"
            api_key = settings.llm.api_key or os.environ.get("ANTHROPIC_API_KEY", "")
            if api_key:
                checks.append((
                    "LLM API Key",
                    "✅",
                    f"Provider: {provider}, Key starts with: {api_key[:8]}…",
                ))
            else:
                checks.append((
                    "LLM API Key",
                    "❌",
                    "No API key found (check GETAJOB_LLM__API_KEY or ANTHROPIC_API_KEY)",
                ))
                critical_fail = True
        except Exception as exc:
            checks.append(("LLM API Key", "❌", f"Config error: {exc}"))
            critical_fail = True

        # ── 3. Database connectivity ────────────────────────────────────────
        if settings is not None:
            try:
                db = settings.database
                from sqlalchemy import text

                async def _probe_db() -> None:
                    engine = create_engine()
                    try:
                        async with engine.connect() as conn:
                            await conn.execute(text("SELECT 1"))
                    finally:
                        await engine.dispose()

                try:
                    await asyncio.wait_for(_probe_db(), timeout=5.0)
                    checks.append((
                        "Database",
                        "✅",
                        f"Connected: {db.host}:{db.port}/{db.database}",
                    ))
                except TimeoutError:
                    checks.append((
                        "Database",
                        "❌",
                        f"Timed out after 5s: {db.host}:{db.port}/{db.database}",
                    ))
                    critical_fail = True
                except Exception as exc:
                    checks.append(("Database", "❌", f"Connection failed: {exc}"))
                    critical_fail = True
            except Exception as exc:
                checks.append(("Database", "❌", f"Config error: {exc}"))
                critical_fail = True

        # ── 4. Config files ────────────────────────────────────────────────
        project_root = Path(__file__).resolve().parent.parent
        env_ok = (project_root / ".env").exists()
        yaml_ok = (project_root / "config" / "settings.yaml").exists()
        tpl_ok = (project_root / "env.template").exists()

        parts = [
            f"{'✅' if env_ok else '❌'} .env",
            f"{'✅' if yaml_ok else '❌'} config/settings.yaml",
            f"{'✅' if tpl_ok else '❌'} env.template",
        ]
        checks.append(("Config Files", "✅" if env_ok else "⚠", "  ".join(parts)))

        # ── 5. Browser (Playwright) ─────────────────────────────────────────
        import importlib.util

        playwright_ok = importlib.util.find_spec("playwright") is not None

        if playwright_ok:
            checks.append(("Browser (Playwright)", "✅", "Playwright is installed"))
        else:
            checks.append((
                "Browser (Playwright)",
                "❌",
                "Not installed - run: playwright install chromium",
            ))

        # ── 6. Data directories ────────────────────────────────────────────
        data_dir = settings.data_dir if settings else Path.cwd() / "data"
        existing: list[str] = []
        missing: list[str] = []

        def _check_dir(path: Path, label: str) -> None:
            (existing if path.exists() else missing).append(label)

        _check_dir(data_dir, "data")
        _check_dir(data_dir / "profiles", "data/profiles")
        _check_dir(data_dir / "resumes", "data/resumes")
        _check_dir(data_dir / "cover_letters", "data/cover_letters")

        if missing:
            detail = " ".join(f"✅ {d}" for d in existing)
            detail += " | Missing: " + " ".join(f"❌ {d}" for d in missing)
            checks.append(("Data Directories", "⚠", detail))
        else:
            detail = " ".join(f"✅ {d}" for d in existing)
            checks.append(("Data Directories", "✅", detail))

        # ── 7. Docker (optional) ───────────────────────────────────────────
        import shutil

        docker_path = shutil.which("docker")
        if docker_path:
            checks.append(("Docker", "✅", f"Found: {docker_path}"))
        else:
            checks.append(("Docker", "-", "Not found (optional)"))

        # ── Render table ──────────────────────────────────────────────────
        table = Table(title="System Health", border_style="blue")
        table.add_column("Check", style="cyan", no_wrap=True)
        table.add_column("Status", justify="center")
        table.add_column("Detail")

        status_colors = {
            "✅": "[green]✅[/]",
            "❌": "[red]❌[/]",
            "⚠": "[yellow]⚠[/]",
            "-": "[dim]-[/]",
        }
        for name, status, detail in checks:
            table.add_row(name, status_colors.get(status, status), detail)

        console.print()
        console.print(table)
        console.print()

        # ── Summary panel ─────────────────────────────────────────────────
        if critical_fail:
            console.print(
                Panel(
                    "[bold red]✗  Some critical checks failed.[/]\n\n"
                    "  Run [cyan]getajob init[/] to set up your configuration.",
                    border_style="red",
                    title="Doctor Summary",
                )
            )
        elif any(s in ("⚠", "❌") for _, s, _ in checks if s != "-"):
            console.print(
                Panel(
                    "[bold yellow]⚠  All critical checks passed, but some items need attention.[/]",
                    border_style="yellow",
                    title="Doctor Summary",
                )
            )
        else:
            console.print(
                Panel(
                    "[bold green]✓  All checks passed![/]  Your system is ready to run GetAJob.",
                    border_style="green",
                    title="Doctor Summary",
                )
            )

    _run_async(_run())


@app.command()
def setup(
    drop_first: bool = typer.Option(
        False,
        "--drop-first",
        help="Drop existing tables before creating (destructive!).",
    ),
) -> None:
    """First-time setup -- create database tables and initialise the schema.

    Uses :func:`~core.database.run_migrations` to create all ORM tables.
    In production, use Alembic migrations instead of this command.

    After tables are created, ensures required data directories exist and
    prints a summary of what was set up.
    """
    console.print(Panel.fit("[bold yellow]⚙️  First-Time Setup[/]", border_style="yellow"))

    async def _run() -> None:
        engine = create_engine()
        try:
            # ── Database ──────────────────────────────────────────────────────
            console.print("  Creating database tables...")
            await run_migrations(engine, drop_first=drop_first)
            console.print("  [green]✓[/] Database schema ready.")

            # ── Data directories ──────────────────────────────────────────────
            settings = get_settings()
            data_dir = settings.data_dir
            data_dir.mkdir(parents=True, exist_ok=True)
            console.print(f"  [green]✓[/] Data directory: {data_dir}")

            # Additional subdirectories.
            for sub in ("profiles", "resumes", "cover_letters", "screenshots"):
                (data_dir / sub).mkdir(parents=True, exist_ok=True)
            console.print("  [green]✓[/] Data subdirectories created.")

            # Check for .env file.
            env_path = Path.cwd() / ".env"
            if env_path.exists():
                console.print(f"  [green]✓[/] Environment file found: {env_path}")
            else:
                env_template = Path.cwd() / "env.template"
                if env_template.exists():
                    console.print(
                        "  [yellow]⚠[/] No .env file found. "
                        "Copy env.template to .env and configure it:\n"
                        "       cp env.template .env"
                    )
                else:
                    console.print(
                        "  [yellow]⚠[/] No .env file found. Create one with your configuration."
                    )

            # ── Summary ───────────────────────────────────────────────────────
            console.print()
            console.print(
                Panel(
                    "[green]✓[/] Setup complete!\n\n"
                    "  [bold]Next steps:[/]\n"
                    "  1. Configure [cyan].env[/] with your API keys\n"
                    "  2. Run [cyan]getajob run[/] to start discovering jobs\n"
                    "  3. Run [cyan]getajob serve[/] to open the approval queue\n",
                    border_style="green",
                    title="Setup Complete",
                )
            )

        except Exception as exc:
            err_console.print(f"[red]✗[/] Setup failed: {exc}")
            raise typer.Exit(code=1) from exc
        finally:
            await engine.dispose()

    _run_async(_run())


# ── Profile commands ───────────────────────────────────────────────────────


@profile_app.command()
def show() -> None:
    """Show the currently active profile.

    Displays name, email, location, skills, and work authorisation
    from the database in a formatted table.
    """

    async def _run() -> None:
        engine = None
        try:
            from core.database import create_engine
            from profile_engine.profile_store import ProfileStore

            engine = create_engine()
            store = ProfileStore(engine)
            profiles = await store.list_profiles(limit=1)

            if not profiles:
                console.print("[yellow]No profile configured. Run 'getajob init' to create one.[/]")
                return

            profile = profiles[0]

            table = Table(title="User Profile", border_style="blue")
            table.add_column("Field", style="cyan", no_wrap=True)
            table.add_column("Value")

            table.add_row("Name", profile.name or "")
            table.add_row("Email", profile.email or "")
            table.add_row("Location", profile.location or "[dim]not set[/]")

            if profile.skills:
                skills_str = ", ".join(s.name for s in profile.skills)
            else:
                skills_str = "[dim]none[/]"
            table.add_row("Skills", skills_str)
            table.add_row("Work Authorization", profile.work_authorization or "[dim]not set[/]")

            console.print(table)
        except Exception as exc:
            err_console.print(f"[red]✗[/] Could not load profile: {exc}")
        finally:
            if engine is not None:
                await engine.dispose()

    _run_async(_run())


@profile_app.command()
def update() -> None:
    """Update profile fields via interactive prompts.

    Shows current values; press Enter to keep a field unchanged.
    Only changed fields are sent to the database.
    """

    async def _run() -> None:
        engine = None
        try:
            from core.database import create_engine
            from core.schemas import ProfileUpdate, SkillSchema
            from profile_engine.profile_store import ProfileStore

            engine = create_engine()
            store = ProfileStore(engine)
            profiles = await store.list_profiles(limit=1)

            if not profiles:
                console.print(
                    "[yellow]No profile configured. Run 'getajob init' to create one first.[/]"
                )
                return

            current = profiles[0]
            console.print(Panel.fit("[bold cyan]✏️  Update Profile[/]", border_style="cyan"))
            console.print("[dim]Press Enter to keep the current value.[/]\n")

            # Interactive prompts with current values as defaults.
            name = typer.prompt("  Name", default=current.name or "")
            email = typer.prompt("  Email", default=current.email or "")
            location = typer.prompt("  Location", default=current.location or "")

            current_skills_str = ", ".join(s.name for s in current.skills) if current.skills else ""
            skills_str = typer.prompt("  Skills (comma-separated)", default=current_skills_str)

            work_auth = typer.prompt(
                "  Work Authorization", default=current.work_authorization or ""
            )

            # Build update payload with only changed fields.
            update_data: dict[str, Any] = {}

            if name.strip() and name.strip() != (current.name or ""):
                update_data["name"] = name.strip()
            if email.strip() and email.strip() != (current.email or ""):
                update_data["email"] = email.strip()
            if location.strip() and location.strip() != (current.location or ""):
                update_data["location"] = location.strip()

            # Skills: comma-separated string -> list[SkillSchema].
            if skills_str.strip():
                new_skills = [s.strip() for s in skills_str.split(",") if s.strip()]
                old_skills = [s.name for s in current.skills] if current.skills else []
                if new_skills != old_skills:
                    update_data["skills"] = [SkillSchema(name=s) for s in new_skills]
            elif current.skills:
                # User explicitly cleared the skills field.
                update_data["skills"] = []

            if work_auth.strip() and work_auth.strip() != (current.work_authorization or ""):
                update_data["work_authorization"] = work_auth.strip()
            elif not work_auth.strip() and current.work_authorization:
                update_data["work_authorization"] = ""

            if not update_data:
                console.print("[yellow]No changes made.[/]")
                return

            updated = await store.update_profile(
                current.id,
                ProfileUpdate(**update_data),
            )

            # Confirmation table.
            field_labels = {
                "name": "Name",
                "email": "Email",
                "location": "Location",
                "skills": "Skills",
                "work_authorization": "Work Authorization",
            }
            updated_values = {
                "name": updated.name or "",
                "email": updated.email or "",
                "location": updated.location or "",
                "skills": (
                    ", ".join(s.name for s in updated.skills) if updated.skills else "[dim]none[/]"
                ),
                "work_authorization": updated.work_authorization or "[dim]not set[/]",
            }

            console.print("\n[green]✓[/] Profile updated successfully.")
            table = Table(border_style="green", show_header=False)
            table.add_column("Field", style="bold cyan")
            table.add_column("Value")

            for field_name in update_data:
                table.add_row(
                    field_labels.get(field_name, field_name.capitalize()),
                    updated_values.get(field_name, ""),
                )

            console.print(table)
        except Exception as exc:
            err_console.print(f"[red]✗[/] Could not update profile: {exc}")
        finally:
            if engine is not None:
                await engine.dispose()

    _run_async(_run())


# ── Vector commands ─────────────────────────────────────────────────────────


@vector_app.command(name="list")
def vector_list() -> None:
    """List all configured search vectors from config/settings.yaml.

    Displays a Rich-formatted table with name, keywords, locations, and
    remote preference for each configured search vector.
    """
    project_root = Path(__file__).resolve().parent.parent
    yaml_path = project_root / "config" / "settings.yaml"

    if not yaml_path.exists():
        console.print(
            "[yellow]No search vectors configured. Run 'getajob init' to set up defaults.[/]"
        )
        raise typer.Exit()

    with yaml_path.open("r") as f:
        data = yaml.safe_load(f) or {}

    vectors = data.get("search_vectors", [])
    if not vectors:
        console.print(
            "[yellow]No search vectors configured. Run 'getajob init' to set up defaults.[/]"
        )
        raise typer.Exit()

    table = Table(title="Search Vectors", border_style="blue")
    table.add_column("Name", style="cyan", no_wrap=True)
    table.add_column("Keywords", style="green")
    table.add_column("Locations", style="yellow")
    table.add_column("Remote", justify="center")

    for vec in vectors:
        # Use explicit name or fall back to first two roles.
        name = vec.get("name") or ", ".join(vec.get("roles", ["(unnamed)"])[:2])
        kw_list = vec.get("keywords", [])
        keywords = ", ".join(kw_list[:5])
        if len(kw_list) > 5:
            keywords += "…"

        loc_list = vec.get("locations", [])
        locations = ", ".join(loc_list) if loc_list else "[dim]any[/]"

        is_remote = any(loc.strip().lower() == "remote" for loc in loc_list)
        remote_str = "[green]✓[/]" if is_remote else "[red]✗[/]"

        table.add_row(name, keywords, locations, remote_str)

    console.print(table)


@vector_app.command(name="add")
def vector_add() -> None:
    """Add a new search vector with interactive prompts.

    Walks through the required fields (name, keywords) and optional fields
    (location, remote preference), then appends the new vector to the
    search_vectors list in config/settings.yaml.
    """
    project_root = Path(__file__).resolve().parent.parent
    yaml_path = project_root / "config" / "settings.yaml"

    console.print(Panel.fit("[bold green]+  Add Search Vector[/]", border_style="green"))

    # ── Interactive prompts ────────────────────────────────────────────
    vec_name = typer.prompt("  Vector name")
    console.print("  [dim]e.g. 'Backend Engineer' or 'Frontend Developer'[/]")

    keywords_str = typer.prompt("  Keywords (comma-separated)")
    console.print("  [dim]e.g. python, go, kubernetes, aws[/]")

    location = typer.prompt("  Location (optional, press Enter to skip)", default="")
    remote = typer.confirm("  Remote only?", default=True)

    # ── Build vector ───────────────────────────────────────────────────
    keywords = [k.strip() for k in keywords_str.split(",") if k.strip()]

    locations: list[str] = []
    if location.strip():
        locations.append(location.strip())
    if remote and "remote" not in [loc.strip().lower() for loc in locations]:
        locations.insert(0, "remote")

    new_vector: dict[str, Any] = {
        "name": vec_name,
        "keywords": keywords,
        "locations": locations,
    }

    # ── Read / update YAML ─────────────────────────────────────────────
    if yaml_path.exists():
        with yaml_path.open("r") as f:
            data: dict[str, Any] = yaml.safe_load(f) or {}
    else:
        data = {}

    vectors = data.setdefault("search_vectors", [])
    vectors.append(new_vector)

    with yaml_path.open("w") as f:
        yaml.safe_dump(
            data,
            f,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )

    # ── Confirmation ───────────────────────────────────────────────────
    console.print()
    table = Table(border_style="green", show_header=False)
    table.add_column("Field", style="bold cyan")
    table.add_column("Value")
    table.add_row("Name", vec_name)
    table.add_row("Keywords", ", ".join(keywords))
    table.add_row(
        "Locations",
        ", ".join(locations) if locations else "[dim]any[/]",
    )
    table.add_row("Remote", "[green]Yes[/]" if remote else "[red]No[/]")
    console.print(table)
    console.print(f"\n[green]✓[/] Vector '[bold]{vec_name}[/]' added successfully.")


# ── Helpers ─────────────────────────────────────────────────────────────────


def _write_default_search_vectors(project_root: Path) -> None:
    """Replace ``search_vectors`` in ``config/settings.yaml`` with defaults.

    Writes three starter search vectors (Software Engineer, Data Scientist,
    Product Manager) to help the user get started immediately.  Existing
    top-level keys (rate limits, ATS profiles, etc.) are preserved.
    """
    yaml_path = project_root / "config" / "settings.yaml"

    default_vectors = [
        {
            "roles": ["software engineer"],
            "keywords": [
                "python",
                "typescript",
                "go",
                "rust",
                "aws",
                "kubernetes",
            ],
            "locations": ["remote"],
            "seniority": ["senior", "staff"],
            "sources": ["linkedin", "indeed", "greenhouse", "workday", "lever"],
            "max_applications_per_day": 50,
        },
        {
            "roles": ["data scientist", "ml engineer"],
            "keywords": [
                "python",
                "pytorch",
                "tensorflow",
                "sql",
                "machine learning",
            ],
            "locations": ["remote"],
            "seniority": ["senior", "staff"],
            "sources": ["linkedin", "indeed", "greenhouse"],
            "max_applications_per_day": 25,
        },
        {
            "roles": ["product manager"],
            "keywords": [
                "product strategy",
                "agile",
                "analytics",
            ],
            "locations": ["remote"],
            "seniority": ["senior", "staff"],
            "sources": ["linkedin", "greenhouse"],
            "max_applications_per_day": 25,
        },
    ]

    if yaml_path.exists():
        with yaml_path.open("r") as f:
            data = yaml.safe_load(f) or {}
    else:
        data = {}

    data["search_vectors"] = default_vectors

    with yaml_path.open("w") as f:
        yaml.safe_dump(
            data,
            f,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )


def _run_async(coro: Coroutine[Any, Any, Any]) -> None:
    """Run an async coroutine in a new event loop.

    Catches :exc:`KeyboardInterrupt` for clean shutdown on Ctrl+C.
    """
    try:
        asyncio.run(coro)
    except KeyboardInterrupt:
        console.print("\n[yellow]Interrupted by user.[/]")
        sys.exit(0)
    except typer.Exit:
        raise
    except Exception as exc:
        err_console.print(f"\n[red]✗[/] {exc}")
        sys.exit(1)


def _check_settings() -> None:
    """Warn the user if critical settings are misconfigured.

    Checks for:
    - Mock LLM provider (no real AI calls).
    - Missing encryption key (PII stored in plaintext).
    """
    settings = get_settings()

    if settings.llm.provider == "mock":
        console.print("[yellow]⚠ Using mock LLM client -- no real AI calls will be made.[/]")

    if not settings.security.encryption_key:
        console.print(
            "[yellow]⚠ Encryption key not set -- "
            "PII will NOT be encrypted at rest.[/]\n"
            "  Set GETAJOB_SECURITY__ENCRYPTION_KEY in your .env file."
        )


def _print_result_table(result: dict[str, Any], title: str = "Results") -> None:
    """Print a pipeline result dict as a Rich table.

    Args:
        result: Dict with string keys and int/float values.
        title: Title displayed above the table.
    """
    table = Table(title=title, border_style="blue")
    table.add_column("Metric", style="cyan")
    table.add_column("Count", justify="right", style="bold")

    for key, value in result.items():
        if isinstance(value, (int, float)):
            style = "green" if value > 0 else "dim"
            label = key.replace("_", " ").title()
            table.add_row(label, str(value), style=style)

    console.print(table)


# ── Entry point ─────────────────────────────────────────────────────────────

app.add_typer(profile_app)
app.add_typer(vector_app)

if __name__ == "__main__":
    app()
